# Generated by Django 4.0.1 on 2022-01-28 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drfapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Values',
            new_name='Skill',
        ),
        migrations.RenameModel(
            old_name='Skills',
            new_name='Value',
        ),
    ]
