# Generated by Django 4.0.1 on 2022-01-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drfapi', '0004_alter_experience_owner_alter_skill_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='experiences',
            field=models.ManyToManyField(null=True, to='drfapi.Experience'),
        ),
        migrations.AlterField(
            model_name='value',
            name='experiences',
            field=models.ManyToManyField(null=True, to='drfapi.Experience'),
        ),
    ]
