# Generated by Django 4.0.1 on 2022-01-29 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drfapi', '0005_alter_skill_experiences_alter_value_experiences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='experiences',
            field=models.ManyToManyField(blank=True, to='drfapi.Experience'),
        ),
        migrations.AlterField(
            model_name='value',
            name='experiences',
            field=models.ManyToManyField(blank=True, to='drfapi.Experience'),
        ),
    ]
